version: 2
updates:
  - directory: .github/workflows
    package-ecosystem: github-actions
    patterns:
      - '*'
    rebase-strategy: auto
    assignees:
      - glektarssza
    labels:
      - Dependency
    commit-message:
      prefix: '[Dependabot] '
    pull-request-branch-name:
      separator: /
    schedule:
      interval: weekly
      day: wednesday
      time: '12:00'
      timezone: Canada/Mountain
